import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
   topicPageContainer: {
      height: '100%',
   },
   blankHeaders: {
      height: 50,
      position: 'relative',
      backgroundColor: 'black',
   },
   flatListContainer: {
      flexDirection: 'row',
   },
   imageStyle: {
      width: 100,
      height: 100,
   },
   imageUserStyle: {
      width: 50,
      height: 50,
      zIndex: 1,
      backgroundColor: 'white',
      borderRadius: 8,
   },
   topicParentWrap: {
      width: '100%',
      flexDirection: 'row',
   },
   topicChildrenText: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      padding: 10,
   },
   imageHeaderBanner: {
      width: 316,
      height: 150,
      paddingBottom: 16,
      zIndex: 2,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white',
      borderRadius: 8,
   },
   ImageHeaderBannerWrap: {
      justifyContent: 'center',
      alignItems: 'center',
   },
   searchInputWrap: {
      backgroundColor: '#313131',
      borderRadius: 8,
      marginHorizontal: 30,
      paddingLeft: 16,
      marginVertical: 16,
      paddingVertical: 8,
      alignItems: 'center',
      flexDirection: 'row',
   },
   searchInput: {
      borderColor: 'none',
      borderWidth: 0,
      color: 'white',
      paddingVertical: 4,
      paddingLeft: 4,
      width: '90%',
   },
   headerWrap: {
      height: '35%',
      backgroundColor: 'black',
      marginBottom: '20%',
   },
   userNameWrap: {
      backgroundColor: '#C67C4E',
      padding: 8,
      borderRadius: 16,
   },
   userName: {
      color: 'white',
      fontStyle: 'italic',
      fontWeight: 'bold',
      fontSize: 12,
   },
   userBarWrap: {
      height: '30%',
      justifyContent: 'space-between',
      color: 'white',
      paddingTop: 10,
      backgroundColor: 'black',
      alignItems: 'center',
      flexDirection: 'row',
      paddingHorizontal: 32,
   },
   topicChildWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#EAEAEA',
   },
   itemChildrenWrap: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      margin: 5,
      backgroundColor: 'black',
      padding: 8,
      borderBottomLeftRadius: 16,
      borderTopRightRadius: 16,
   },
   itemChildTextName: {
      fontWeight: '600',
      fontSize: 12,
      color: '#ffff',
   },
   topicParentNameWrap: {
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 4,
      width: '100%',
      backgroundColor: '#C67C4E',
   },
   topicParentName: {
      fontSize: 18,
      fontWeight: '700',
      fontStyle: 'italic',
      color: 'white',
      paddingHorizontal: 16,
      paddingVertical: 8,
      textAlign: 'center',
      paddingLeft: 12,
   },
   //modal styles
   centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
      position: 'absolute',
      right: 75,
      top: 80,
   },
   modalView: {
      backgroundColor: 'white',
      borderRadius: 20,
      padding: 16,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
         width: 0,
         height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
   },
   iconX: {
      position: 'absolute',
      top: 5,
      right: 8,
   },
   profileOption: {
      marginTop: 16,
      padding: 8,
      borderWidth: 1,
      textAlign: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
   },
   logoutOption: {
      marginTop: 8,
      padding: 8,
      borderWidth: 1,
      textAlign: 'center',
      justifyContent: 'center',
      alignContent: 'center',
      width: '100%',
   },
   modalText: {
      fontSize: 16,
      marginBottom: 15,
      textAlign: 'center',
   },
});
